### ISSUE TITLE
Kütüphane

### ISSUE THREAD

**Issue by besimaltnok** [MeteALANLI/FTPClient#1]
FTP işlemleriniz için ftplib modülünü kullanabilirsiniz. Burada da bir kaynak mevcut : 
https://github.com/besimaltnok/PFE/blob/master/modules/m_ftplib.md

Bir şey olursa destek vermek isterim. sduyazilim :+1:

**Comment by MeteALANLI** [comment]
Çok teşekkürler Besim işimize yarayacağı kanısındayım.
